Add Session C: Meshing with cjdns and messing with secure-scuttlebutt
ournetworks/2017-mini-conf pull request #11
Opened 2016-11-26 20:29 UTC by benhylau

2016-11-27 01:11 UTC, benhylau commented
@dcwalk ready for merge when you approve

2016-11-28 01:26 UTC, dcwalk commented on sessions/session-c.md
> +This hands-on session begins with [configuring a Raspberry Pi](https://github.com/tomeshnet/prototype-cjdns-pi2) as a [cjdns](https://github.com/cjdelisle/cjdns) mesh node. Then we will enable the IP
Can we pull out the materials comment out either to the top or below this para and the scuttlebutt one?

2016-11-28 01:27 UTC, dcwalk commented on sessions/session-c.md
> +# Session C: Meshing with cjdns and messing with secure-scuttlebutt
Dig this! But I think we need a short title (the second could be like the after-colon part?)
e.g. "Build a Mesh Node: Meshing with cjdns and messing with secure-scuttlebutt" and I'll use the short one on the website schedule?

2016-11-28 01:31 UTC, dcwalk requested changes
Thanks @benhylau! just a couple quick bits (sorry should have been clearer about stuff on the template)

2016-11-28 01:31 UTC, dcwalk commented on sessions/session-c.md
> +We will run [secure-scuttlebutt](https://github.com/ssbc/secure-scuttlebutt) on our ad-hoc mesh, which keeps an append-only database on each node with peer-to-peer replication across the network, bac
unclear what 'backing' means here? Also could we link out to wiki or explain what DNS is (or expand the acronym and link out)?

2016-11-28 01:31 UTC, dcwalk commented on sessions/session-c.md
> +- Use the cjdns protocol to set up an encrypted mesh network of Raspberry Pi's
Maybe link to cjdns here or on first use?

2016-11-28 01:31 UTC, dcwalk commented on sessions/session-c.md
> +- Configure an IP tunnel to exit all Internet traffic at a distant cjdns node, essentially having the Raspberry Pi serve as a VPN router
again, link for IP tunnel explanation and VPN?

2016-11-28 01:31 UTC, dcwalk commented on sessions/session-c.md
> +- Ethernet cable
Are these all requests for participants? 
Can you list an estimate of kits you'll have? usb adapters, ethernet cable, etc...? 
then I can add in what we can borrow from semaphore!

2016-11-28 01:32 UTC, dcwalk commented
Also whoa, just used the review bit and that was odd "changes requested" sounds too harsh :(

2016-11-28 06:32 UTC, benhylau commented on sessions/session-c.md
> +- Use the cjdns protocol to set up an encrypted mesh network of Raspberry Pi's
It was linked on first use.

2016-11-28 13:18 UTC, dcwalk approved these changes

2016-11-28 13:18 UTC, dcwalk commented on sessions/session-c.md
> +- Use the cjdns protocol to set up an encrypted mesh network of Raspberry Pi's
aha whoops! thx

2016-11-28 13:20 UTC, merged